#!/bin/bash
set -e

npm i -g @devcontainers/cli

declare -a baseImages=(
    "ubuntu:bionic"
    "debian:10"
    "ubuntu:focal"
    "ubuntu:jammy"
    "debian:11"
    "mcr.microsoft.com/devcontainers/base:ubuntu"
    "mcr.microsoft.com/devcontainers/base:debian")
for baseImage in "${baseImages[@]}"
do
    echo $baseImage
    devcontainer features test --skip-scenarios -f powershell -i $baseImage .
done
devcontainer features test -f powershell --skip-autogenerated  .

